apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  namespace: investment-app
spec:
  type: LoadBalancer # <--- EXPOSES APP TO THE OUTSIDE WORLD
  selector:
    app: portfolio-service
  ports:
    - protocol: TCP
      port: 80      # We will access it on Port 80 (standard HTTP)
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-service-deployment
  namespace: investment-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-service
  template:
    metadata:
      labels:
        app: portfolio-service
    spec:
      containers:
        - name: portfolio-service
          image: portfolio-service:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            # 1. Database Connection (Service Discovery)
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/investment_db?allowPublicKeyRetrieval=true&useSSL=false
            # 2. Database Secrets
            - name: SPRING_DATASOURCE_USERNAME
              value: pankhuri
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: user-password
            # 3. Stock Service Connection (Service Discovery)
            - name: STOCK_SERVICE_URL
              value: http://stock-service:8080